$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train-model
display_name: Train Candidate Models
version: "1.0"
type: command

inputs:
  input_data:
    type: uri_file
    description: Preprocessed training dataset (CSV)

  candidates:
    type: string
    description: JSON string with candidate models and hyperparameters

  feature_groups:
    type: string
    description: JSON string with feature group definitions

  random_state:
    type: integer
    default: 42
    description: Random seed for reproducibility

  cv_folds:
    type: integer
    default: 5
    description: Number of cross-validation folds

  threshold:
    type: number
    default: 0.5
    description: Decision threshold for classification metrics (probability of default cutoff)

# No outputs since models are registered directly into MLflow/AML registry

code: ./

environment: azureml:credit-env:1

command: >
  python train.py
  --input_data ${{inputs.input_data}}
  --candidates ${{inputs.candidates}}
  --feature_groups ${{inputs.feature_groups}}
  --random_state ${{inputs.random_state}}
  --cv_folds ${{inputs.cv_folds}}
  --threshold ${{inputs.threshold}}
