# ===============================
# Training Configuration
# ===============================
# This file defines everything needed for the TRAIN component.
# It will be parsed in the submit_pipeline script and passed into train.py.
#
# Contents:
# - selection_criteria: how to choose champion model from candidates
# - global_hyperparams: parameters that affect training for ALL candidates
# - candidates: list of candidate models, their hyperparams, CV score from R&D,
#   and any custom tags (dataset version, author, etc.)
#
# Notes:
# - All candidate models must specify:
#     * model: string identifier ("logreg", "rf", "xgb")
#     * params: dict of hyperparameters (keys must match constructor args)
#     * cv_score: mean CV AUC from R&D (reference, not used in training)
#     * tags: optional dict of metadata
# - Threshold: used to compute precision/recall/F1 for positive class
#   (policy-driven, bank-specific decision).
# - CV folds: number of folds for cross-validation in train.py
#
# Example usage:
# training_config.yaml → loaded in submit_pipeline.py → serialized as JSON
# → passed to train.py via --candidates and --selection_criteria args.

selection_criteria:
  primary: auc_roc         # always rank by ROC AUC first
  tiebreaker:
    - metric: recall       # if AUC is close, prefer higher recall
      equality_threshold: 0.05      # tolerance for considering AUC "close"
  min_threshold: 0.70      # reject all if no candidate reaches 0.70 AUC

global_hyperparams:
  cv_folds: 5              # number of CV folds in train.py
  decision_threshold: 0.08           # decision threshold for classifying default risk

candidates:
  - model: xgb
    params:
      learning_rate: 0.1
      max_depth: 3
      n_estimators: 100
      subsample: 1.0
      scale_pos_weight: 2.33
    cv_score: 0.792
    tags:
      dataset_version: "german_credit_v1"
      phase: "R&D"
      author: "ml_team"

  - model: rf
    params:
      n_estimators: 200
      max_depth: 5
      min_samples_split: 2
      class_weight: balanced
    cv_score: 0.790
    tags:
      dataset_version: "german_credit_v1"
      phase: "R&D"
      author: "ml_team"
