name: CI - Code Quality and Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 pyyaml

      - name: Lint with flake8
        run: |
          flake8 . --count --max-complexity=10 --max-line-length=100 --statistics

      - name: Run unit tests
        run: pytest -q

      - name: Validate component YAMLs
        run: |
          python -c "import yaml, glob; [yaml.safe_load(open(f)) for f in glob.glob('**/*.yaml', recursive=True)]"
