name: CT - Retrain on Schedule or Drift

on:
  schedule:
    - cron: "0 2 * * 1"   # every Monday at 2 AM UTC
  workflow_dispatch:       # manual trigger
  repository_dispatch:     # allows external systems (like a drift monitor) to trigger this

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Submit retraining pipeline
        run: python submit_pipeline.py --drift-check
        env:
          SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
          COMPUTE_NAME: ${{ secrets.AZURE_COMPUTE_NAME }}
          RAW_DATA_PATH: ${{ secrets.AZURE_RAW_DATA_PATH }}
